export interface Quote {
  text: string
  author: string
}

// One per day, indexed by days-since-start mod 75 — deterministic, offline,
// and it never repeats within a single clean run.
export const QUOTES: Quote[] = [
  { text: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.', author: 'Will Durant' },
  { text: 'The best time to plant a tree was 20 years ago. The second best time is now.', author: 'Chinese proverb' },
  { text: 'It is not that we have a short time to live, but that we waste a lot of it.', author: 'Seneca' },
  { text: 'You do not rise to the level of your goals. You fall to the level of your systems.', author: 'James Clear' },
  { text: 'What we fear doing most is usually what we most need to do.', author: 'Tim Ferriss' },
  { text: 'Amateurs sit and wait for inspiration, the rest of us just get up and go to work.', author: 'Stephen King' },
  { text: 'The impediment to action advances action. What stands in the way becomes the way.', author: 'Marcus Aurelius' },
  { text: 'Do the hard jobs first. The easy jobs will take care of themselves.', author: 'Dale Carnegie' },
  { text: 'A year from now you may wish you had started today.', author: 'Karen Lamb' },
  { text: 'Discipline is choosing between what you want now and what you want most.', author: 'Abraham Lincoln (attributed)' },
  { text: 'The successful warrior is the average man, with laser-like focus.', author: 'Bruce Lee' },
  { text: 'How we spend our days is, of course, how we spend our lives.', author: 'Annie Dillard' },
  { text: 'Nothing in this world can take the place of persistence.', author: 'Calvin Coolidge' },
  { text: 'If you quit on the process, you are quitting on the result.', author: 'Idowu Koyenikan' },
  { text: 'Deep work is the ability to focus without distraction on a cognitively demanding task.', author: 'Cal Newport' },
  { text: 'Every action you take is a vote for the type of person you wish to become.', author: 'James Clear' },
  { text: 'It always seems impossible until it is done.', author: 'Nelson Mandela' },
  { text: 'First say to yourself what you would be; and then do what you have to do.', author: 'Epictetus' },
  { text: 'The chief cause of failure and unhappiness is trading what we want most for what we want right now.', author: 'Zig Ziglar' },
  { text: 'Reading is to the mind what exercise is to the body.', author: 'Joseph Addison' },
  { text: 'You have power over your mind — not outside events. Realize this, and you will find strength.', author: 'Marcus Aurelius' },
  { text: 'Whether you think you can, or you think you can’t — you’re right.', author: 'Henry Ford' },
  { text: 'The man who moves a mountain begins by carrying away small stones.', author: 'Confucius' },
  { text: 'What you do every day matters more than what you do once in a while.', author: 'Gretchen Rubin' },
  { text: 'Motivation is what gets you started. Habit is what keeps you going.', author: 'Jim Ryun' },
  { text: 'The only way to learn a new programming language is by writing programs in it.', author: 'Dennis Ritchie' },
  { text: 'An investment in knowledge pays the best interest.', author: 'Benjamin Franklin' },
  { text: 'Success is the sum of small efforts, repeated day in and day out.', author: 'Robert Collier' },
  { text: 'Don’t count the days, make the days count.', author: 'Muhammad Ali' },
  { text: 'The expert in anything was once a beginner.', author: 'Helen Hayes' },
  { text: 'Well begun is half done.', author: 'Aristotle' },
  { text: 'If I have seen further it is by standing on the shoulders of giants.', author: 'Isaac Newton' },
  { text: 'Genius is one percent inspiration and ninety-nine percent perspiration.', author: 'Thomas Edison' },
  { text: 'The way to get started is to quit talking and begin doing.', author: 'Walt Disney' },
  { text: 'Concentrate all your thoughts upon the work in hand.', author: 'Alexander Graham Bell' },
  { text: 'Either you run the day or the day runs you.', author: 'Jim Rohn' },
  { text: 'Small daily improvements over time lead to stunning results.', author: 'Robin Sharma' },
  { text: 'He who has a why to live can bear almost any how.', author: 'Friedrich Nietzsche' },
  { text: 'Knowing is not enough; we must apply. Willing is not enough; we must do.', author: 'Johann Wolfgang von Goethe' },
  { text: 'I fear not the man who has practiced 10,000 kicks once, but the man who has practiced one kick 10,000 times.', author: 'Bruce Lee' },
  { text: 'You miss 100% of the shots you don’t take.', author: 'Wayne Gretzky' },
  { text: 'Someday is not a day of the week.', author: 'Janet Dailey' },
  { text: 'Quality is not an act, it is a habit.', author: 'Aristotle' },
  { text: 'Focus is a matter of deciding what things you’re not going to do.', author: 'John Carmack' },
  { text: 'A reader lives a thousand lives before he dies. The man who never reads lives only one.', author: 'George R.R. Martin' },
  { text: 'Hard choices, easy life. Easy choices, hard life.', author: 'Jerzy Gregorek' },
  { text: 'Sow a habit and you reap a character; sow a character and you reap a destiny.', author: 'Stephen Covey' },
  { text: 'Perseverance is not a long race; it is many short races one after the other.', author: 'Walter Elliot' },
  { text: 'The secret of getting ahead is getting started.', author: 'Mark Twain (attributed)' },
  { text: 'You can’t build a reputation on what you are going to do.', author: 'Henry Ford' },
  { text: 'Rivers know this: there is no hurry. We shall get there some day.', author: 'A.A. Milne' },
  { text: 'Patience and perseverance have a magical effect before which difficulties disappear.', author: 'John Quincy Adams' },
  { text: 'To improve is to change; to be perfect is to change often.', author: 'Winston Churchill' },
  { text: 'The mind is not a vessel to be filled, but a fire to be kindled.', author: 'Plutarch' },
  { text: 'Nothing will work unless you do.', author: 'Maya Angelou' },
  { text: 'Absorb what is useful, discard what is not, add what is uniquely your own.', author: 'Bruce Lee' },
  { text: 'Doing the best at this moment puts you in the best place for the next moment.', author: 'Oprah Winfrey' },
  { text: 'There is no substitute for hard work.', author: 'Thomas Edison' },
  { text: 'A little progress each day adds up to big results.', author: 'Satya Nani' },
  { text: 'Never mistake motion for action.', author: 'Ernest Hemingway' },
  { text: 'If you’re going through hell, keep going.', author: 'Winston Churchill (attributed)' },
  { text: 'The scholar’s ink lasts longer than the martyr’s blood.', author: 'Irish proverb' },
  { text: 'Learning never exhausts the mind.', author: 'Leonardo da Vinci' },
  { text: 'Fall seven times, stand up eight.', author: 'Japanese proverb' },
  { text: 'What is not started today is never finished tomorrow.', author: 'Johann Wolfgang von Goethe' },
  { text: 'While we are postponing, life speeds by.', author: 'Seneca' },
  { text: 'Great things are done by a series of small things brought together.', author: 'Vincent van Gogh' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
  { text: 'Energy and persistence conquer all things.', author: 'Benjamin Franklin' },
  { text: 'The difference between ordinary and extraordinary is that little extra.', author: 'Jimmy Johnson' },
  { text: 'You are never too old to set another goal or to dream a new dream.', author: 'C.S. Lewis' },
  { text: 'Act as if what you do makes a difference. It does.', author: 'William James' },
  { text: 'Strive not to be a success, but rather to be of value.', author: 'Albert Einstein' },
  { text: 'The best way out is always through.', author: 'Robert Frost' },
  { text: 'Finish each day and be done with it. Tomorrow is a new day; begin it well.', author: 'Ralph Waldo Emerson' },
]

/** Deterministic quote for a given day: stable all day, changes at midnight. */
export function quoteForDay(startDate: string | null, today: string): Quote {
  if (!startDate) return QUOTES[0]
  const days = Math.round(
    (Date.parse(`${today}T00:00:00Z`) - Date.parse(`${startDate}T00:00:00Z`)) /
      86_400_000,
  )
  return QUOTES[((days % QUOTES.length) + QUOTES.length) % QUOTES.length]
}
